target 'Mich' do
    use_frameworks!
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
    pod 'Google/SignIn'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Messaging'
    pod 'Firebase/Database'
    pod 'Alamofire'
    pod 'JSQMessagesViewController'
    pod 'ObjectMapper'
    pod 'Nuke'
    pod 'AlamofireImage', '~> 3.1'
    pod 'Preheat'
    pod 'GoogleMaps', '~> 2.4'
    pod 'GooglePlaces', '~> 2.4'
    pod 'GooglePlacePicker'
    pod 'XLPagerTabStrip', '~> 8.0'
end
